### ISSUE TITLE
Spatial data for municipalities is simplified

### ISSUE THREAD

**Issue by mz8i** [npalomin/shi_dataset_cdmx#1]
The `alcaldias.geojson` file contains simplified shapes - the borders of the alcaldias sometimes differ from the outer borders of the individual colonias. This can make the map a bit chaotic at times, especially in denser areas. Would it be possible to get a file that is not simplified (or simplified less)?

**Comment by npalomin** [comment]
We tried to fix this (through simplification, etc) but we don't have enough information. Agree it can make the map a bit chaotic but we think other than that it shouldn't affect navigation performance. This problem is typical of inconsistent data or data with different resolution. Let's work as it is for now but feel free to raise the issue if you think is urgent.

**Comment by mz8i** [comment]
Right, thanks. So I assume we don't have access to a file that would contain all the colonias in the displayed area, and could be aggregated up to alcaldias?

**Comment by npalomin** [comment]
Exactly, we don't have access to a file that would contain all the Colonias in the displayed area neither have a "perfect" correspondence with the Alcaldias boundaries
